name: UI Tests

on: workflow_dispatch

jobs:
  ui-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Checkout gh-pages repository (if exists)
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: ./.github/gh-pages
        continue-on-error: true  # Продолжать даже если ветки нет

      - name: Run UI-tests via docker-compose
        env:
          LOGIN: ${{ secrets.LOGIN }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          docker-compose up --exit-code-from regression || true

      - name: Prepare Allure results directory
        run: |
          mkdir -p allure-results/history
          # Копируем историю только если она существует
          if [ -d "./.github/gh-pages/history" ]; then
            echo "Copying existing history..."
            cp -R ./.github/gh-pages/history/* allure-results/history/
          else
            echo "No history found - starting fresh"
            mkdir -p allure-results/history
          fi

      - name: Generate Allure report
        run: |
          docker-compose run regression /bin/sh -c "allure generate allure-results --clean -o allure-report"

      - name: Update Allure history
        run: |
          mkdir -p ./.github/gh-pages/history
          cp -R allure-report/history/* ./.github/gh-pages/history/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.CI_TOKEN }}
          branch: gh-pages
          folder: allure-report
          clean: true