name: UI Tests

on: workflow_dispatch

jobs:
  ui-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Checkout gh-pages repository (if exists)
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: ./.github/gh-pages
        continue-on-error: true

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker

      - name: Run UI-tests via docker compose
        env:
          LOGIN: ${{ secrets.LOGIN }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          docker compose up --exit-code-from regression || true

      - name: Prepare Allure results directory
        run: |
          mkdir -p allure-results/history
          if [ -d "./.github/gh-pages/history" ]; then
            echo "Copying existing history..."
            cp -R ./.github/gh-pages/history/* allure-results/history/
          else
            echo "No history found - starting fresh"
          fi

      - name: Install Allure
        run: |
          sudo curl -o allure-2.13.8.tgz -Ls https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.13.8/allure-commandline-2.13.8.tgz
          sudo tar -zxvf allure-2.13.8.tgz -C /opt/
          sudo ln -sf /opt/allure-2.13.8/bin/allure /usr/local/bin/allure
          allure --version

      - name: Generate Allure report
        run: |
          allure generate allure-results --clean -o allure-report

      - name: Update Allure history
        run: |
          mkdir -p ./.github/gh-pages/history
          cp -R allure-report/history/* ./.github/gh-pages/history/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.CI_TOKEN }}
          branch: gh-pages
          folder: allure-report
          clean: true